@startuml
hide circle
'skinparam linetype ortho

entity game{
  Game Information, synced with backend plugin
  ..
  + id: //number [PK]//
  --
  * name: //text : ""Plugin name""//
  * active: //boolean  : ""unused""//
  * number_of_players: //number : ""unused""//
}

entity play{
  Play Information, a play between players
  ..
  + id: //number [PK]//
  --
  *game: //number : [FK]//
  *game_state: //simple-json  : ""All turns, chronological""//
  *created_at: //timestamp : ""When was the play launched?""//
  *updated_at: //timestamp : ""When was the last move?""//
}

entity playslug{
  player of play
  ..
  + id: //number [PK]//
  --
  *play: //number : [FK]//
  *player: //number : [FK]//
  *slug: //string : ""The player slug""//
  *symbol: //string : ""Symbol of the player""//
  *created_at: //timestamp : ""useless""//
}

entity player{
  player aka user of games2click
  ..
    + id: //number [PK]//
    --
    *browserid: //string : Unique id of browser//
}

play::game -u-  game : 1:n
playslug::play --  play : 1:n
playslug::player -r-  player : n:1

@enduml
