@startuml

component Browser {
}

node "Docker Compose" {
    [Gateway] <<nginx>>
    [Frontend] <<react>>
    [certbot] <<service timer>>
    [Backend] <<node.js>>
    database "Database" <<Postgres>>

    node "Volumes" {
        [certs]
    }
}

Browser -r-> Gateway
Gateway -u-> certs : ssl
Gateway -r-> Frontend : request /*
Gateway -d-> Backend : request /api/*
Backend -r-> "Database"

certbot -l-> certs : Lets Encrypt
@enduml
