@startuml

component Browser {
}

node "Docker Compose" {
    [Gateway] <<nginx>>
    [Frontend] <<react>>
    [Backend] <<node.js>>
    database "Arcadia DB" <<Postgres>>
}

Browser -r- Gateway
Gateway -r- Frontend : request /*
Gateway -d- Backend : request /api/*
Backend -r- "Arcadia DB"

@enduml
