@startuml

component Browser {
}

node "Docker Compose" {
    [Gateway] <<nginx>>

    [Frontend] <<react>>
    [certbot] <<service timer>>
    [Backend] <<node.js>>
    database "Database" <<Postgres>>

    node "Volumes" {
        [certs]
    }

    package "Analytics" {
        [Matomo_Web]
        [Matomo_App]
        database "Matomo_DB" <<mariadb>>
    }
}

Browser -r-> Gateway

Gateway -u-> certs : ssl
Gateway -r-> Frontend : request /*
Gateway -d-> Backend : request /api/*
Backend -d-> "Database"

certbot -l-> certs : Lets Encrypt

Gateway --> Matomo_Web : analytics.games2.click
Matomo_Web --> Matomo_App
Matomo_App --> "Matomo_DB"

@enduml
